//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema-lite";
import type { FindManyArgs as $FindManyArgs, FindUniqueArgs as $FindUniqueArgs, FindFirstArgs as $FindFirstArgs, CreateArgs as $CreateArgs, CreateManyArgs as $CreateManyArgs, CreateManyAndReturnArgs as $CreateManyAndReturnArgs, UpdateArgs as $UpdateArgs, UpdateManyArgs as $UpdateManyArgs, UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs, UpsertArgs as $UpsertArgs, DeleteArgs as $DeleteArgs, DeleteManyArgs as $DeleteManyArgs, CountArgs as $CountArgs, AggregateArgs as $AggregateArgs, GroupByArgs as $GroupByArgs, WhereInput as $WhereInput, SelectInput as $SelectInput, IncludeInput as $IncludeInput, OmitInput as $OmitInput, QueryOptions as $QueryOptions } from "@zenstackhq/orm";
import type { SimplifiedPlainResult as $Result, SelectIncludeOmit as $SelectIncludeOmit } from "@zenstackhq/orm";
export type UserFindManyArgs = $FindManyArgs<$Schema, "User">;
export type UserFindUniqueArgs = $FindUniqueArgs<$Schema, "User">;
export type UserFindFirstArgs = $FindFirstArgs<$Schema, "User">;
export type UserCreateArgs = $CreateArgs<$Schema, "User">;
export type UserCreateManyArgs = $CreateManyArgs<$Schema, "User">;
export type UserCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "User">;
export type UserUpdateArgs = $UpdateArgs<$Schema, "User">;
export type UserUpdateManyArgs = $UpdateManyArgs<$Schema, "User">;
export type UserUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "User">;
export type UserUpsertArgs = $UpsertArgs<$Schema, "User">;
export type UserDeleteArgs = $DeleteArgs<$Schema, "User">;
export type UserDeleteManyArgs = $DeleteManyArgs<$Schema, "User">;
export type UserCountArgs = $CountArgs<$Schema, "User">;
export type UserAggregateArgs = $AggregateArgs<$Schema, "User">;
export type UserGroupByArgs = $GroupByArgs<$Schema, "User">;
export type UserWhereInput = $WhereInput<$Schema, "User">;
export type UserSelect = $SelectInput<$Schema, "User">;
export type UserInclude = $IncludeInput<$Schema, "User">;
export type UserOmit = $OmitInput<$Schema, "User">;
export type UserGetPayload<Args extends $SelectIncludeOmit<$Schema, "User", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "User", Args, Options>;
export type AuditLogFindManyArgs = $FindManyArgs<$Schema, "AuditLog">;
export type AuditLogFindUniqueArgs = $FindUniqueArgs<$Schema, "AuditLog">;
export type AuditLogFindFirstArgs = $FindFirstArgs<$Schema, "AuditLog">;
export type AuditLogCreateArgs = $CreateArgs<$Schema, "AuditLog">;
export type AuditLogCreateManyArgs = $CreateManyArgs<$Schema, "AuditLog">;
export type AuditLogCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "AuditLog">;
export type AuditLogUpdateArgs = $UpdateArgs<$Schema, "AuditLog">;
export type AuditLogUpdateManyArgs = $UpdateManyArgs<$Schema, "AuditLog">;
export type AuditLogUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "AuditLog">;
export type AuditLogUpsertArgs = $UpsertArgs<$Schema, "AuditLog">;
export type AuditLogDeleteArgs = $DeleteArgs<$Schema, "AuditLog">;
export type AuditLogDeleteManyArgs = $DeleteManyArgs<$Schema, "AuditLog">;
export type AuditLogCountArgs = $CountArgs<$Schema, "AuditLog">;
export type AuditLogAggregateArgs = $AggregateArgs<$Schema, "AuditLog">;
export type AuditLogGroupByArgs = $GroupByArgs<$Schema, "AuditLog">;
export type AuditLogWhereInput = $WhereInput<$Schema, "AuditLog">;
export type AuditLogSelect = $SelectInput<$Schema, "AuditLog">;
export type AuditLogInclude = $IncludeInput<$Schema, "AuditLog">;
export type AuditLogOmit = $OmitInput<$Schema, "AuditLog">;
export type AuditLogGetPayload<Args extends $SelectIncludeOmit<$Schema, "AuditLog", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "AuditLog", Args, Options>;
export type RefreshTokenFindManyArgs = $FindManyArgs<$Schema, "RefreshToken">;
export type RefreshTokenFindUniqueArgs = $FindUniqueArgs<$Schema, "RefreshToken">;
export type RefreshTokenFindFirstArgs = $FindFirstArgs<$Schema, "RefreshToken">;
export type RefreshTokenCreateArgs = $CreateArgs<$Schema, "RefreshToken">;
export type RefreshTokenCreateManyArgs = $CreateManyArgs<$Schema, "RefreshToken">;
export type RefreshTokenCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "RefreshToken">;
export type RefreshTokenUpdateArgs = $UpdateArgs<$Schema, "RefreshToken">;
export type RefreshTokenUpdateManyArgs = $UpdateManyArgs<$Schema, "RefreshToken">;
export type RefreshTokenUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "RefreshToken">;
export type RefreshTokenUpsertArgs = $UpsertArgs<$Schema, "RefreshToken">;
export type RefreshTokenDeleteArgs = $DeleteArgs<$Schema, "RefreshToken">;
export type RefreshTokenDeleteManyArgs = $DeleteManyArgs<$Schema, "RefreshToken">;
export type RefreshTokenCountArgs = $CountArgs<$Schema, "RefreshToken">;
export type RefreshTokenAggregateArgs = $AggregateArgs<$Schema, "RefreshToken">;
export type RefreshTokenGroupByArgs = $GroupByArgs<$Schema, "RefreshToken">;
export type RefreshTokenWhereInput = $WhereInput<$Schema, "RefreshToken">;
export type RefreshTokenSelect = $SelectInput<$Schema, "RefreshToken">;
export type RefreshTokenInclude = $IncludeInput<$Schema, "RefreshToken">;
export type RefreshTokenOmit = $OmitInput<$Schema, "RefreshToken">;
export type RefreshTokenGetPayload<Args extends $SelectIncludeOmit<$Schema, "RefreshToken", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "RefreshToken", Args, Options>;
