//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/orm/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "postgresql"
    } as const;
    models = {
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("nanoid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                },
                username: {
                    name: "username",
                    type: "String",
                    unique: true
                },
                passwordHash: {
                    name: "passwordHash",
                    type: "String"
                },
                name: {
                    name: "name",
                    type: "String"
                },
                role: {
                    name: "role",
                    type: "Role"
                },
                RefreshToken: {
                    name: "RefreshToken",
                    type: "RefreshToken",
                    array: true,
                    relation: { opposite: "User" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                username: { type: "String" }
            }
        },
        AuditLog: {
            name: "AuditLog",
            fields: {
                timestamp: {
                    name: "timestamp",
                    type: "DateTime",
                    id: true,
                    default: ExpressionUtils.call("now")
                },
                action: {
                    name: "action",
                    type: "String"
                },
                data: {
                    name: "data",
                    type: "Json"
                }
            },
            idFields: ["timestamp"],
            uniqueFields: {
                timestamp: { type: "DateTime" }
            }
        },
        RefreshToken: {
            name: "RefreshToken",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("nanoid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "User"
                    ]
                },
                User: {
                    name: "User",
                    type: "User",
                    relation: { opposite: "RefreshToken", fields: ["userId"], references: ["id"] }
                },
                revoked: {
                    name: "revoked",
                    type: "Boolean",
                    default: false
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        }
    } as const;
    typeDefs = {
        ID: {
            name: "ID",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    default: ExpressionUtils.call("nanoid")
                }
            }
        },
        Timestamps: {
            name: "Timestamps",
            fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                }
            }
        },
        Base: {
            name: "Base",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    default: ExpressionUtils.call("nanoid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                }
            }
        }
    } as const;
    enums = {
        Role: {
            values: {
                SUPERADMIN: "SUPERADMIN",
                ADMIN: "ADMIN",
                USER: "USER"
            }
        }
    } as const;
    authType = "User" as const;
    plugins = {};
}
export const schema = new SchemaType();
