//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/orm/schema";
const _schema = {
    provider: {
        type: "postgresql"
    },
    models: {
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("nanoid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                },
                username: {
                    name: "username",
                    type: "String",
                    unique: true
                },
                passwordHash: {
                    name: "passwordHash",
                    type: "String"
                },
                name: {
                    name: "name",
                    type: "String"
                },
                role: {
                    name: "role",
                    type: "Role"
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                username: { type: "String" }
            }
        },
        AuditLog: {
            name: "AuditLog",
            fields: {
                timestamp: {
                    name: "timestamp",
                    type: "DateTime",
                    id: true,
                    default: ExpressionUtils.call("now")
                },
                action: {
                    name: "action",
                    type: "String"
                },
                data: {
                    name: "data",
                    type: "Json"
                }
            },
            idFields: ["timestamp"],
            uniqueFields: {
                timestamp: { type: "DateTime" }
            }
        }
    },
    typeDefs: {
        ID: {
            name: "ID",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    default: ExpressionUtils.call("nanoid")
                }
            }
        },
        Timestamps: {
            name: "Timestamps",
            fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                }
            }
        },
        Base: {
            name: "Base",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    default: ExpressionUtils.call("nanoid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                }
            }
        }
    },
    enums: {
        Role: {
            values: {
                SUPERADMIN: "SUPERADMIN",
                ADMIN: "ADMIN",
                USER: "USER"
            }
        }
    },
    authType: "User",
    plugins: {}
} as const satisfies SchemaDef;
type Schema = typeof _schema & {
    __brand?: "schema";
};
export const schema: Schema = _schema;
export type SchemaType = Schema;
